export type CountryInfo = {
  name: string;
  dialCode: string;
  emoji: string;
  code: string; // ISO 2-letter
};

export const countries: CountryInfo[] = [
  { "name": "Afghanistan", "code": "AF", "emoji": "🇦🇫", "dialCode": "+93" },
  { "name": "Aland Islands", "code": "AX", "emoji": "🇦🇽", "dialCode": "+358" },
  { "name": "Albania", "code": "AL", "emoji": "🇦🇱", "dialCode": "+355" },
  { "name": "Algeria", "code": "DZ", "emoji": "🇩🇿", "dialCode": "+213" },
  { "name": "American Samoa", "code": "AS", "emoji": "🇦🇸", "dialCode": "+1684" },
  { "name": "Andorra", "code": "AD", "emoji": "🇦🇩", "dialCode": "+376" },
  { "name": "Angola", "code": "AO", "emoji": "🇦🇴", "dialCode": "+244" },
  { "name": "Anguilla", "code": "AI", "emoji": "🇦🇮", "dialCode": "+1264" },
  { "name": "Antarctica", "code": "AQ", "emoji": "🇦🇶", "dialCode": "+672" },
  { "name": "Antigua and Barbuda", "code": "AG", "emoji": "🇦🇬", "dialCode": "+1268" },
  { "name": "Argentina", "code": "AR", "emoji": "🇦🇷", "dialCode": "+54" },
  { "name": "Armenia", "code": "AM", "emoji": "🇦🇲", "dialCode": "+374" },
  { "name": "Aruba", "code": "AW", "emoji": "🇦🇼", "dialCode": "+297" },
  { "name": "Australia", "code": "AU", "emoji": "🇦🇺", "dialCode": "+61" },
  { "name": "Austria", "code": "AT", "emoji": "🇦🇹", "dialCode": "+43" },
  { "name": "Azerbaijan", "code": "AZ", "emoji": "🇦🇿", "dialCode": "+994" },
  { "name": "Bahamas", "code": "BS", "emoji": "🇧🇸", "dialCode": "+1242" },
  { "name": "Bahrain", "code": "BH", "emoji": "🇧🇭", "dialCode": "+973" },
  { "name": "Bangladesh", "code": "BD", "emoji": "🇧🇩", "dialCode": "+880" },
  { "name": "Barbados", "code": "BB", "emoji": "🇧🇧", "dialCode": "+1246" },
  { "name": "Belarus", "code": "BY", "emoji": "🇧🇾", "dialCode": "+375" },
  { "name": "Belgium", "code": "BE", "emoji": "🇧🇪", "dialCode": "+32" },
  { "name": "Belize", "code": "BZ", "emoji": "🇧🇿", "dialCode": "+501" },
  { "name": "Benin", "code": "BJ", "emoji": "🇧🇯", "dialCode": "+229" },
  { "name": "Bermuda", "code": "BM", "emoji": "🇧🇲", "dialCode": "+1441" },
  { "name": "Bhutan", "code": "BT", "emoji": "🇧🇹", "dialCode": "+975" },
  { "name": "Bolivia", "code": "BO", "emoji": "🇧🇴", "dialCode": "+591" },
  { "name": "Bosnia and Herzegovina", "code": "BA", "emoji": "🇧🇦", "dialCode": "+387" },
  { "name": "Botswana", "code": "BW", "emoji": "🇧🇼", "dialCode": "+267" },
  { "name": "Brazil", "code": "BR", "emoji": "🇧🇷", "dialCode": "+55" },
  { "name": "British Indian Ocean Territory", "code": "IO", "emoji": "🇮🇴", "dialCode": "+246" },
  { "name": "Brunei Darussalam", "code": "BN", "emoji": "🇧🇳", "dialCode": "+673" },
  { "name": "Bulgaria", "code": "BG", "emoji": "🇧🇬", "dialCode": "+359" },
  { "name": "Burkina Faso", "code": "BF", "emoji": "🇧🇫", "dialCode": "+226" },
  { "name": "Burundi", "code": "BI", "emoji": "🇧🇮", "dialCode": "+257" },
  { "name": "Cambodia", "code": "KH", "emoji": "🇰🇭", "dialCode": "+855" },
  { "name": "Cameroon", "code": "CM", "emoji": "🇨🇲", "dialCode": "+237" },
  { "name": "Canada", "code": "CA", "emoji": "🇨🇦", "dialCode": "+1" },
  { "name": "Cape Verde", "code": "CV", "emoji": "🇨🇻", "dialCode": "+238" },
  { "name": "Cayman Islands", "code": "KY", "emoji": "🇰🇾", "dialCode": "+1345" },
  { "name": "Central African Republic", "code": "CF", "emoji": "🇨🇫", "dialCode": "+236" },
  { "name": "Chad", "code": "TD", "emoji": "🇹🇩", "dialCode": "+235" },
  { "name": "Chile", "code": "CL", "emoji": "🇨🇱", "dialCode": "+56" },
  { "name": "China", "code": "CN", "emoji": "🇨🇳", "dialCode": "+86" },
  { "name": "Christmas Island", "code": "CX", "emoji": "🇨🇽", "dialCode": "+61" },
  { "name": "Cocos (Keeling) Islands", "code": "CC", "emoji": "🇨🇨", "dialCode": "+61" },
  { "name": "Colombia", "code": "CO", "emoji": "🇨🇴", "dialCode": "+57" },
  { "name": "Comoros", "code": "KM", "emoji": "🇰🇲", "dialCode": "+269" },
  { "name": "Congo", "code": "CG", "emoji": "🇨🇬", "dialCode": "+242" },
  { "name": "Congo, The Democratic Republic of the", "code": "CD", "emoji": "🇨🇩", "dialCode": "+243" },
  { "name": "Cook Islands", "code": "CK", "emoji": "🇨🇰", "dialCode": "+682" },
  { "name": "Costa Rica", "code": "CR", "emoji": "🇨🇷", "dialCode": "+506" },
  { "name": "Cote d'Ivoire", "code": "CI", "emoji": "🇨🇮", "dialCode": "+225" },
  { "name": "Croatia", "code": "HR", "emoji": "🇭🇷", "dialCode": "+385" },
  { "name": "Cuba", "code": "CU", "emoji": "🇨🇺", "dialCode": "+53" },
  { "name": "Cyprus", "code": "CY", "emoji": "🇨🇾", "dialCode": "+357" },
  { "name": "Czech Republic", "code": "CZ", "emoji": "🇨🇿", "dialCode": "+420" },
  { "name": "Denmark", "code": "DK", "emoji": "🇩🇰", "dialCode": "+45" },
  { "name": "Djibouti", "code": "DJ", "emoji": "🇩🇯", "dialCode": "+253" },
  { "name": "Dominica", "code": "DM", "emoji": "🇩🇲", "dialCode": "+1767" },
  { "name": "Dominican Republic", "code": "DO", "emoji": "🇩🇴", "dialCode": "+1849" },
  { "name": "Ecuador", "code": "EC", "emoji": "🇪🇨", "dialCode": "+593" },
  { "name": "Egypt", "code": "EG", "emoji": "🇪🇬", "dialCode": "+20" },
  { "name": "El Salvador", "code": "SV", "emoji": "🇸🇻", "dialCode": "+503" },
  { "name": "Equatorial Guinea", "code": "GQ", "emoji": "🇬🇶", "dialCode": "+240" },
  { "name": "Eritrea", "code": "ER", "emoji": "🇪🇷", "dialCode": "+291" },
  { "name": "Estonia", "code": "EE", "emoji": "🇪🇪", "dialCode": "+372" },
  { "name": "Ethiopia", "code": "ET", "emoji": "🇪🇹", "dialCode": "+251" },
  { "name": "Falkland Islands (Malvinas)", "code": "FK", "emoji": "🇫🇰", "dialCode": "+500" },
  { "name": "Faroe Islands", "code": "FO", "emoji": "🇫🇴", "dialCode": "+298" },
  { "name": "Fiji", "code": "FJ", "emoji": "🇫🇯", "dialCode": "+679" },
  { "name": "Finland", "code": "FI", "emoji": "🇫🇮", "dialCode": "+358" },
  { "name": "France", "code": "FR", "emoji": "🇫🇷", "dialCode": "+33" },
  { "name": "French Guiana", "code": "GF", "emoji": "🇬🇫", "dialCode": "+594" },
  { "name": "French Polynesia", "code": "PF", "emoji": "🇵🇫", "dialCode": "+689" },
  { "name": "Gabon", "code": "GA", "emoji": "🇬🇦", "dialCode": "+241" },
  { "name": "Gambia", "code": "GM", "emoji": "🇬🇲", "dialCode": "+220" },
  { "name": "Georgia", "code": "GE", "emoji": "🇬🇪", "dialCode": "+995" },
  { "name": "Germany", "code": "DE", "emoji": "🇩🇪", "dialCode": "+49" },
  { "name": "Ghana", "code": "GH", "emoji": "🇬🇭", "dialCode": "+233" },
  { "name": "Gibraltar", "code": "GI", "emoji": "🇬🇮", "dialCode": "+350" },
  { "name": "Greece", "code": "GR", "emoji": "🇬🇷", "dialCode": "+30" },
  { "name": "Greenland", "code": "GL", "emoji": "🇬🇱", "dialCode": "+299" },
  { "name": "Grenada", "code": "GD", "emoji": "🇬🇩", "dialCode": "+1473" },
  { "name": "Guadeloupe", "code": "GP", "emoji": "🇬🇵", "dialCode": "+590" },
  { "name": "Guam", "code": "GU", "emoji": "🇬🇺", "dialCode": "+1671" },
  { "name": "Guatemala", "code": "GT", "emoji": "🇬🇹", "dialCode": "+502" },
  { "name": "Guernsey", "code": "GG", "emoji": "🇬🇬", "dialCode": "+44" },
  { "name": "Guinea", "code": "GN", "emoji": "🇬🇳", "dialCode": "+224" },
  { "name": "Guinea-Bissau", "code": "GW", "emoji": "🇬🇼", "dialCode": "+245" },
  { "name": "Guyana", "code": "GY", "emoji": "🇬🇾", "dialCode": "+592" },
  { "name": "Haiti", "code": "HT", "emoji": "🇭🇹", "dialCode": "+509" },
  { "name": "Holy See (Vatican City State)", "code": "VA", "emoji": "🇻🇦", "dialCode": "+379" },
  { "name": "Honduras", "code": "HN", "emoji": "🇭🇳", "dialCode": "+504" },
  { "name": "Hong Kong", "code": "HK", "emoji": "🇭🇰", "dialCode": "+852" },
  { "name": "Hungary", "code": "HU", "emoji": "🇭🇺", "dialCode": "+36" },
  { "name": "Iceland", "code": "IS", "emoji": "🇮🇸", "dialCode": "+354" },
  { "name": "India", "code": "IN", "emoji": "🇮🇳", "dialCode": "+91" },
  { "name": "Indonesia", "code": "ID", "emoji": "🇮🇩", "dialCode": "+62" },
  { "name": "Iran, Islamic Republic of", "code": "IR", "emoji": "🇮🇷", "dialCode": "+98" },
  { "name": "Iraq", "code": "IQ", "emoji": "🇮🇶", "dialCode": "+964" },
  { "name": "Ireland", "code": "IE", "emoji": "🇮🇪", "dialCode": "+353" },
  { "name": "Isle of Man", "code": "IM", "emoji": "🇮🇲", "dialCode": "+44" },
  { "name": "Israel", "code": "IL", "emoji": "🇮🇱", "dialCode": "+972" },
  { "name": "Italy", "code": "IT", "emoji": "🇮🇹", "dialCode": "+39" },
  { "name": "Jamaica", "code": "JM", "emoji": "🇯🇲", "dialCode": "+1876" },
  { "name": "Japan", "code": "JP", "emoji": "🇯🇵", "dialCode": "+81" },
  { "name": "Jersey", "code": "JE", "emoji": "🇯🇪", "dialCode": "+44" },
  { "name": "Jordan", "code": "JO", "emoji": "🇯🇴", "dialCode": "+962" },
  { "name": "Kazakhstan", "code": "KZ", "emoji": "🇰🇿", "dialCode": "+7" },
  { "name": "Kenya", "code": "KE", "emoji": "🇰🇪", "dialCode": "+254" },
  { "name": "Kiribati", "code": "KI", "emoji": "🇰🇮", "dialCode": "+686" },
  { "name": "Korea, Democratic People's Republic of", "code": "KP", "emoji": "🇰🇵", "dialCode": "+850" },
  { "name": "Korea, Republic of", "code": "KR", "emoji": "🇰🇷", "dialCode": "+82" },
  { "name": "Kuwait", "code": "KW", "emoji": "🇰🇼", "dialCode": "+965" },
  { "name": "Kyrgyzstan", "code": "KG", "emoji": "🇰🇬", "dialCode": "+996" },
  { "name": "Lao People's Democratic Republic", "code": "LA", "emoji": "🇱🇦", "dialCode": "+856" },
  { "name": "Latvia", "code": "LV", "emoji": "🇱🇻", "dialCode": "+371" },
  { "name": "Lebanon", "code": "LB", "emoji": "🇱🇧", "dialCode": "+961" },
  { "name": "Lesotho", "code": "LS", "emoji": "🇱🇸", "dialCode": "+266" },
  { "name": "Liberia", "code": "LR", "emoji": "🇱🇷", "dialCode": "+231" },
  { "name": "Libyan Arab Jamahiriya", "code": "LY", "emoji": "🇱🇾", "dialCode": "+218" },
  { "name": "Liechtenstein", "code": "LI", "emoji": "🇱🇮", "dialCode": "+423" },
  { "name": "Lithuania", "code": "LT", "emoji": "🇱🇹", "dialCode": "+370" },
  { "name": "Luxembourg", "code": "LU", "emoji": "🇱🇺", "dialCode": "+352" },
  { "name": "Macao", "code": "MO", "emoji": "🇲🇴", "dialCode": "+853" },
  { "name": "Macedonia", "code": "MK", "emoji": "🇲🇰", "dialCode": "+389" },
  { "name": "Madagascar", "code": "MG", "emoji": "🇲🇬", "dialCode": "+261" },
  { "name": "Malawi", "code": "MW", "emoji": "🇲🇼", "dialCode": "+265" },
  { "name": "Malaysia", "code": "MY", "emoji": "🇲🇾", "dialCode": "+60" },
  { "name": "Maldives", "code": "MV", "emoji": "🇲🇻", "dialCode": "+960" },
  { "name": "Mali", "code": "ML", "emoji": "🇲🇱", "dialCode": "+223" },
  { "name": "Malta", "code": "MT", "emoji": "🇲🇹", "dialCode": "+356" },
  { "name": "Marshall Islands", "code": "MH", "emoji": "🇲🇭", "dialCode": "+692" },
  { "name": "Martinique", "code": "MQ", "emoji": "🇲🇶", "dialCode": "+596" },
  { "name": "Mauritania", "code": "MR", "emoji": "🇲🇷", "dialCode": "+222" },
  { "name": "Mauritius", "code": "MU", "emoji": "🇲🇺", "dialCode": "+230" },
  { "name": "Mayotte", "code": "YT", "emoji": "🇾🇹", "dialCode": "+262" },
  { "name": "Mexico", "code": "MX", "emoji": "🇲🇽", "dialCode": "+52" },
  { "name": "Micronesia, Federated States of", "code": "FM", "emoji": "🇫🇲", "dialCode": "+691" },
  { "name": "Moldova, Republic of", "code": "MD", "emoji": "🇲🇩", "dialCode": "+373" },
  { "name": "Monaco", "code": "MC", "emoji": "🇲🇨", "dialCode": "+377" },
  { "name": "Mongolia", "code": "MN", "emoji": "🇲🇳", "dialCode": "+976" },
  { "name": "Montenegro", "code": "ME", "emoji": "🇲🇪", "dialCode": "+382" },
  { "name": "Montserrat", "code": "MS", "emoji": "🇲🇸", "dialCode": "+1664" },
  { "name": "Morocco", "code": "MA", "emoji": "🇲🇦", "dialCode": "+212" },
  { "name": "Mozambique", "code": "MZ", "emoji": "🇲🇿", "dialCode": "+258" },
  { "name": "Myanmar", "code": "MM", "emoji": "🇲🇲", "dialCode": "+95" },
  { "name": "Namibia", "code": "NA", "emoji": "🇳🇦", "dialCode": "+264" },
  { "name": "Nauru", "code": "NR", "emoji": "🇳🇷", "dialCode": "+674" },
  { "name": "Nepal", "code": "NP", "emoji": "🇳🇵", "dialCode": "+977" },
  { "name": "Netherlands", "code": "NL", "emoji": "🇳🇱", "dialCode": "+31" },
  { "name": "New Caledonia", "code": "NC", "emoji": "🇳🇨", "dialCode": "+687" },
  { "name": "New Zealand", "code": "NZ", "emoji": "🇳🇿", "dialCode": "+64" },
  { "name": "Nicaragua", "code": "NI", "emoji": "🇳🇮", "dialCode": "+505" },
  { "name": "Niger", "code": "NE", "emoji": "🇳🇪", "dialCode": "+227" },
  { "name": "Nigeria", "code": "NG", "emoji": "🇳🇬", "dialCode": "+234" },
  { "name": "Niue", "code": "NU", "emoji": "🇳🇺", "dialCode": "+683" },
  { "name": "Norfolk Island", "code": "NF", "emoji": "🇳🇫", "dialCode": "+672" },
  { "name": "Northern Mariana Islands", "code": "MP", "emoji": "🇲🇵", "dialCode": "+1670" },
  { "name": "Norway", "code": "NO", "emoji": "🇳🇴", "dialCode": "+47" },
  { "name": "Oman", "code": "OM", "emoji": "🇴🇲", "dialCode": "+968" },
  { "name": "Pakistan", "code": "PK", "emoji": "🇵🇰", "dialCode": "+92" },
  { "name": "Palau", "code": "PW", "emoji": "🇵🇼", "dialCode": "+680" },
  { "name": "Palestinian Territory, Occupied", "code": "PS", "emoji": "🇵🇸", "dialCode": "+970" },
  { "name": "Panama", "code": "PA", "emoji": "🇵🇦", "dialCode": "+507" },
  { "name": "Papua New Guinea", "code": "PG", "emoji": "🇵🇬", "dialCode": "+675" },
  { "name": "Paraguay", "code": "PY", "emoji": "🇵🇾", "dialCode": "+595" },
  { "name": "Peru", "code": "PE", "emoji": "🇵🇪", "dialCode": "+51" },
  { "name": "Philippines", "code": "PH", "emoji": "🇵🇭", "dialCode": "+63" },
  { "name": "Pitcairn", "code": "PN", "emoji": "🇵🇳", "dialCode": "+64" },
  { "name": "Poland", "code": "PL", "emoji": "🇵🇱", "dialCode": "+48" },
  { "name": "Portugal", "code": "PT", "emoji": "🇵🇹", "dialCode": "+351" },
  { "name": "Puerto Rico", "code": "PR", "emoji": "🇵🇷", "dialCode": "+1787" },
  { "name": "Qatar", "code": "QA", "emoji": "🇶🇦", "dialCode": "+974" },
  { "name": "Reunion", "code": "RE", "emoji": "🇷🇪", "dialCode": "+262" },
  { "name": "Romania", "code": "RO", "emoji": "🇷🇴", "dialCode": "+40" },
  { "name": "Russian Federation", "code": "RU", "emoji": "🇷🇺", "dialCode": "+7" },
  { "name": "Rwanda", "code": "RW", "emoji": "🇷🇼", "dialCode": "+250" },
  { "name": "Saint Barthelemy", "code": "BL", "emoji": "🇧🇱", "dialCode": "+590" },
  { "name": "Saint Helena", "code": "SH", "emoji": "🇸🇭", "dialCode": "+290" },
  { "name": "Saint Kitts and Nevis", "code": "KN", "emoji": "🇰🇳", "dialCode": "+1869" },
  { "name": "Saint Lucia", "code": "LC", "emoji": "🇱🇨", "dialCode": "+1758" },
  { "name": "Saint Martin", "code": "MF", "emoji": "🇲🇫", "dialCode": "+590" },
  { "name": "Saint Pierre and Miquelon", "code": "PM", "emoji": "🇵🇲", "dialCode": "+508" },
  { "name": "Saint Vincent and the Grenadines", "code": "VC", "emoji": "🇻🇨", "dialCode": "+1784" },
  { "name": "Samoa", "code": "WS", "emoji": "🇼🇸", "dialCode": "+685" },
  { "name": "San Marino", "code": "SM", "emoji": "🇸🇲", "dialCode": "+378" },
  { "name": "Sao Tome and Principe", "code": "ST", "emoji": "🇸🇹", "dialCode": "+239" },
  { "name": "Saudi Arabia", "code": "SA", "emoji": "🇸🇦", "dialCode": "+966" },
  { "name": "Senegal", "code": "SN", "emoji": "🇸🇳", "dialCode": "+221" },
  { "name": "Serbia", "code": "RS", "emoji": "🇷🇸", "dialCode": "+381" },
  { "name": "Seychelles", "code": "SC", "emoji": "🇸🇨", "dialCode": "+248" },
  { "name": "Sierra Leone", "code": "SL", "emoji": "🇸🇱", "dialCode": "+232" },
  { "name": "Singapore", "code": "SG", "emoji": "🇸🇬", "dialCode": "+65" },
  { "name": "Sint Maarten", "code": "SX", "emoji": "🇸🇽", "dialCode": "+1" },
  { "name": "Slovakia", "code": "SK", "emoji": "🇸🇰", "dialCode": "+421" },
  { "name": "Slovenia", "code": "SI", "emoji": "🇸🇮", "dialCode": "+386" },
  { "name": "Solomon Islands", "code": "SB", "emoji": "🇸🇧", "dialCode": "+677" },
  { "name": "Somalia", "code": "SO", "emoji": "🇸🇴", "dialCode": "+252" },
  { "name": "South Africa", "code": "ZA", "emoji": "🇿🇦", "dialCode": "+27" },
  { "name": "South Sudan", "code": "SS", "emoji": "🇸🇸", "dialCode": "+211" },
  { "name": "Spain", "code": "ES", "emoji": "🇪🇸", "dialCode": "+34" },
  { "name": "Sri Lanka", "code": "LK", "emoji": "🇱🇰", "dialCode": "+94" },
  { "name": "Sudan", "code": "SD", "emoji": "🇸🇩", "dialCode": "+249" },
  { "name": "Suriname", "code": "SR", "emoji": "🇸🇷", "dialCode": "+597" },
  { "name": "Svalbard and Jan Mayen", "code": "SJ", "emoji": "🇸🇯", "dialCode": "+47" },
  { "name": "Swaziland", "code": "SZ", "emoji": "🇸🇿", "dialCode": "+268" },
  { "name": "Sweden", "code": "SE", "emoji": "🇸🇪", "dialCode": "+46" },
  { "name": "Switzerland", "code": "CH", "emoji": "🇨🇭", "dialCode": "+41" },
  { "name": "Syrian Arab Republic", "code": "SY", "emoji": "🇸🇾", "dialCode": "+963" },
  { "name": "Taiwan", "code": "TW", "emoji": "🇹🇼", "dialCode": "+886" },
  { "name": "Tajikistan", "code": "TJ", "emoji": "🇹🇯", "dialCode": "+992" },
  { "name": "Tanzania, United Republic of", "code": "TZ", "emoji": "🇹🇿", "dialCode": "+255" },
  { "name": "Thailand", "code": "TH", "emoji": "🇹🇭", "dialCode": "+66" },
  { "name": "Timor-Leste", "code": "TL", "emoji": "🇹🇱", "dialCode": "+670" },
  { "name": "Togo", "code": "TG", "emoji": "🇹🇬", "dialCode": "+228" },
  { "name": "Tokelau", "code": "TK", "emoji": "🇹🇰", "dialCode": "+690" },
  { "name": "Tonga", "code": "TO", "emoji": "🇹🇴", "dialCode": "+676" },
  { "name": "Trinidad and Tobago", "code": "TT", "emoji": "🇹🇹", "dialCode": "+1868" },
  { "name": "Tunisia", "code": "TN", "emoji": "🇹🇳", "dialCode": "+216" },
  { "name": "Turkey", "code": "TR", "emoji": "🇹🇷", "dialCode": "+90" },
  { "name": "Turkmenistan", "code": "TM", "emoji": "🇹🇲", "dialCode": "+993" },
  { "name": "Turks and Caicos Islands", "code": "TC", "emoji": "🇹🇨", "dialCode": "+1649" },
  { "name": "Tuvalu", "code": "TV", "emoji": "🇹🇻", "dialCode": "+688" },
  { "name": "Uganda", "code": "UG", "emoji": "🇺🇬", "dialCode": "+256" },
  { "name": "Ukraine", "code": "UA", "emoji": "🇺🇦", "dialCode": "+380" },
  { "name": "United Arab Emirates", "code": "AE", "emoji": "🇦🇪", "dialCode": "+971" },
  { "name": "United Kingdom", "code": "GB", "emoji": "🇬🇧", "dialCode": "+44" },
  { "name": "United States", "code": "US", "emoji": "🇺🇸", "dialCode": "+1" },
  { "name": "Uruguay", "code": "UY", "emoji": "🇺🇾", "dialCode": "+598" },
  { "name": "Uzbekistan", "code": "UZ", "emoji": "🇺🇿", "dialCode": "+998" },
  { "name": "Vanuatu", "code": "VU", "emoji": "🇻🇺", "dialCode": "+678" },
  { "name": "Venezuela", "code": "VE", "emoji": "🇻🇪", "dialCode": "+58" },
  { "name": "Vietnam", "code": "VN", "emoji": "🇻🇳", "dialCode": "+84" },
  { "name": "Virgin Islands, British", "code": "VG", "emoji": "🇻🇬", "dialCode": "+1284" },
  { "name": "Virgin Islands, U.s.", "code": "VI", "emoji": "🇻🇮", "dialCode": "+1340" },
  { "name": "Wallis and Futuna", "code": "WF", "emoji": "🇼🇫", "dialCode": "+681" },
  { "name": "Western Sahara", "code": "EH", "emoji": "🇪🇭", "dialCode": "+212" },
  { "name": "Yemen", "code": "YE", "emoji": "🇾🇪", "dialCode": "+967" },
  { "name": "Zambia", "code": "ZM", "emoji": "🇿🇲", "dialCode": "+260" },
  { "name": "Zimbabwe", "code": "ZW", "emoji": "🇿🇼", "dialCode": "+263" }
];
